allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.70.0'
  - '@typescript-eslint/parser@8.70.0'
  - '@typescript-eslint/project-service@8.70.0'
  - '@typescript-eslint/scope-manager@8.70.0'
  - '@typescript-eslint/tsconfig-utils@8.70.0'
  - '@typescript-eslint/type-utils@8.70.0'
  - '@typescript-eslint/types@8.70.0'
  - '@typescript-eslint/typescript-estree@8.70.0'
  - '@typescript-eslint/utils@8.70.0'
  - '@typescript-eslint/visitor-keys@8.70.0'
  - typescript-eslint@8.70.0
