import { skillImage } from '@/utils/assets';

/** Custom skill icons in public/images/skills/ */
const SKILL_ICONS: Record<string, string> = {
  Angular: 'angular.svg',
  VueJS: 'vueJS.svg',
  NuxtJS: 'nuxtJS.svg',
  NestJS: 'nestJS.svg',
  'Node.js': 'nodeJS.svg',
  nodeJS: 'nodeJS.svg',
  React: 'reactJS.svg',
  ReactJS: 'reactJS.svg',
  JavaScript: 'javaScript.svg',
  TypeScript: 'typeScript.svg',
  'C#': 'cSharp.svg',
  Java: 'java.svg',
  SQL: 'sql.svg',
  Express: 'expressJS.svg',
  ExpressJS: 'expressJS.svg',
  'Bash Script': 'bashScript.svg',
  Docker: 'docker.svg',
  Cypress: 'cypress.svg',
  Testing: 'testing.svg',
  'API Testing': 'apiTesting.svg',
  'Smoke Testing': 'smokeTesting.svg',
  AI: 'claude.svg',
  SEO: 'seo.svg',
  'REST API': 'restAPI.svg',
  RESTAPI: 'restAPI.svg',
  Agile: 'agile.svg',
  Git: 'git.svg',
  Vite: 'vite.svg',
  AWS: 'aws.svg',
  Azure: 'azure.svg',
  Linux: 'linux.svg',
  'System Design': 'systemDesign.svg',
  Elasticsearch: 'elasticsearch.svg',
  PostgreSQL: 'postgreSQL.svg',
  MongoDB: 'mongoDB.svg',
  'Argo CD': 'argoCd.svg',
  ArgoCD: 'argoCd.svg',
  Helm: 'helm.svg',
  Terraform: 'terraform.svg',
  Ansible: 'ansible.svg',
  Kafka: 'kafka.svg',
  Python: 'python.svg',
  Prometheus: 'prometheus.svg',
  Grafana: 'grafana.svg',
  Datadog: 'datadog.svg',
  Splunk: 'splunk.svg',
  OpenTelemetry: 'openTelemetry.svg',
  DHCP: 'dhcp.svg',
  DNS: 'dns.svg',
  'Active Directory': 'activeDirectory.svg',
  'TCP/IP': 'tcpIp.svg',
  Routing: 'routing.svg',
  Switching: 'switching.svg',
  Subnetting: 'subnetting.svg',
  MikroTik: 'mikroTik.svg',
  Apache: 'apache.svg',
  Firewall: 'firewall.svg',
  SSH: 'ssh.svg',
  LDAP: 'ldap.svg',
  Samba: 'samba.svg',
  VLAN: 'vlan.svg',
  NAT: 'nat.svg',
  OSPF: 'ospf.svg',
  VPN: 'vpn.svg',
  systemd: 'systemd.svg',
  LVM: 'lvm.svg',
  Winbox: 'winbox.svg',
};

/** Maps display labels to simple-icons slug (public/images/skills/{slug}.svg) */
const TECH_SLUG_MAP: Record<string, string> = {
  JavaScript: 'javascript',
  'JavaScript ES6+': 'javascript',
  TypeScript: 'typescript',
  'C#': 'csharp',
  '.NET': 'dotnet',
  dotnet: 'dotnet',
  Angular: 'angular',
  Nx: 'nx',
  'Node.js': 'nodedotjs',
  nodeJS: 'nodedotjs',
  NestJS: 'nestjs',
  VueJS: 'vuedotjs',
  NuxtJS: 'nuxtdotjs',
  React: 'react',
  ReactJS: 'react',
  NextJS: 'nextdotjs',
  Express: 'express',
  ExpressJS: 'express',
  'CI/CD': 'githubactions',
  AWS: 'amazonaws',
  Azure: 'azure',
  Docker: 'docker',
  AI: 'claude',
  Git: 'git',
  Linux: 'linux',
  Agile: 'scrum',
  Scrum: 'scrum',
  Jira: 'jira',
  HTML: 'html5',
  'Semantic HTML / HTML5': 'html5',
  CSS: 'css3',
  'CSS / SCSS / PostCSS': 'css3',
  Sass: 'sass',
  'Tailwind CSS': 'tailwindcss',
  Bootstrap: 'bootstrap',
  PostgreSQL: 'postgresql',
  MongoDB: 'mongodb',
  SQL: 'mysql',
  GraphQL: 'graphql',
  tRPC: 'trpc',
  Kubernetes: 'kubernetes',
  Vitest: 'vitest',
  Playwright: 'playwright',
  Jest: 'jest',
  Cypress: 'cypress',
  Webpack: 'webpack',
  Vite: 'vite',
  Pinia: 'pinia',
  NgRx: 'ngrx',
  Redux: 'redux',
  RxJS: 'reactivex',
  Storybook: 'storybook',
  ChartJS: 'chartdotjs',
  'GitHub Actions': 'githubactions',
  'GitHub Copilot': 'github',
  Cursor: 'cursor',
  OpenAI: 'openai',
  Anthropic: 'anthropic',
  Gemini: 'googlegemini',
  Datadog: 'datadog',
  Java: 'java',
  Spring: 'spring',
  'REST API': 'openapiinitiative',
  MikroTik: 'mikrotik',
  'Active Directory': 'microsoft',
  'PCI tokenization': 'visa',
};

export function techIconSlug(label: string): string | undefined {
  if (TECH_SLUG_MAP[label]) return TECH_SLUG_MAP[label];
  const normalized = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '')
    .replace(/dotjs$/, 'dotjs');
  return normalized.length > 1 ? normalized : undefined;
}

export function techIconPath(label: string): string | undefined {
  if (SKILL_ICONS[label]) return skillImage(SKILL_ICONS[label]);
  const slug = techIconSlug(label);
  return slug ? skillImage(`${slug}.svg`) : undefined;
}
