import { skillImage } from '@/utils/assets';

/** Custom skill icons in public/images/skills/ */
const SKILL_ICONS: Record<string, string> = {
  Angular: 'angular.png',
  VueJS: 'vueJS.png',
  NuxtJS: 'nuxtJS.png',
  NestJS: 'nestJS.png',
  'Node.js': 'nodeJS.png',
  nodeJS: 'nodeJS.png',
  React: 'reactJS.png',
  ReactJS: 'reactJS.png',
  JavaScript: 'javaScript.png',
  TypeScript: 'typeScript.png',
  'C#': 'cSharp.png',
  SQL: 'sql.png',
  Express: 'expressJS.png',
  ExpressJS: 'expressJS.png',
  'Bash Script': 'bashScript.png',
  Docker: 'docker.png',
  Cypress: 'cypress.svg',
  Testing: 'testing.png',
  'API Testing': 'apiTesting.png',
  'Smoke Testing': 'smokeTesting.png',
  SEO: 'seo.png',
  'REST API': 'restAPI.png',
  RESTAPI: 'restAPI.png',
  Agile: 'agile.png',
  Git: 'git.png',
  Vite: 'vite.png',
  AWS: 'aws.png',
  Azure: 'azure.png',
  Linux: 'linux.png',
  'System Design': 'systemDesign.png',
  Elasticsearch: 'elasticsearch.png',
  PostgreSQL: 'postgreSQL.png',
  MongoDB: 'mongoDB.png',
  'Argo CD': 'argoCd.png',
  ArgoCD: 'argoCd.png',
  Helm: 'helm.svg',
  Terraform: 'terraform.png',
  Ansible: 'ansible.png',
  Kafka: 'kafka.svg',
  Python: 'python.png',
  Prometheus: 'prometheus.png',
  Grafana: 'grafana.png',
  Datadog: 'datadog.png',
  Splunk: 'splunk.png',
  OpenTelemetry: 'openTelemetry.png',
  DHCP: 'dhcp.png',
  DNS: 'dns.png',
  'Active Directory': 'activeDirectory.png',
  'TCP/IP': 'tcpIp.png',
  Routing: 'routing.png',
  Switching: 'switching.png',
  Subnetting: 'subnetting.png',
  MikroTik: 'mikroTik.png',
  Apache: 'apache.png',
  Firewall: 'firewall.png',
  SSH: 'ssh.png',
  LDAP: 'ldap.png',
  Samba: 'samba.png',
  VLAN: 'vlan.png',
  NAT: 'nat.png',
  OSPF: 'ospf.png',
  VPN: 'vpn.png',
  systemd: 'systemd.png',
  LVM: 'lvm.png',
  Winbox: 'winbox.png',
};

/** Maps display labels to simple-icons slug (public/images/skills/{slug}.svg) */
const TECH_SLUG_MAP: Record<string, string> = {
  JavaScript: 'javascript',
  'JavaScript ES6+': 'javascript',
  TypeScript: 'typescript',
  'C#': 'csharp',
  '.NET': 'dotnet',
  dotnet: 'dotnet',
  Angular: 'angular',
  Nx: 'nx',
  'Node.js': 'nodedotjs',
  nodeJS: 'nodedotjs',
  NestJS: 'nestjs',
  VueJS: 'vuedotjs',
  NuxtJS: 'nuxtdotjs',
  React: 'react',
  ReactJS: 'react',
  NextJS: 'nextdotjs',
  Express: 'express',
  ExpressJS: 'express',
  'CI/CD': 'githubactions',
  AWS: 'amazonaws',
  Azure: 'azure',
  Docker: 'docker',
  AI: 'openai',
  Git: 'git',
  Linux: 'linux',
  Agile: 'scrum',
  Scrum: 'scrum',
  Jira: 'jira',
  HTML: 'html5',
  'Semantic HTML / HTML5': 'html5',
  CSS: 'css3',
  'CSS / SCSS / PostCSS': 'css3',
  Sass: 'sass',
  'Tailwind CSS': 'tailwindcss',
  Bootstrap: 'bootstrap',
  PostgreSQL: 'postgresql',
  MongoDB: 'mongodb',
  SQL: 'mysql',
  GraphQL: 'graphql',
  tRPC: 'trpc',
  Kubernetes: 'kubernetes',
  Vitest: 'vitest',
  Playwright: 'playwright',
  Jest: 'jest',
  Cypress: 'cypress',
  Webpack: 'webpack',
  Vite: 'vite',
  Pinia: 'pinia',
  NgRx: 'ngrx',
  Redux: 'redux',
  RxJS: 'reactivex',
  Storybook: 'storybook',
  ChartJS: 'chartdotjs',
  'GitHub Actions': 'githubactions',
  'GitHub Copilot': 'github',
  Cursor: 'cursor',
  OpenAI: 'openai',
  Anthropic: 'anthropic',
  Gemini: 'googlegemini',
  Datadog: 'datadog',
  'REST API': 'openapiinitiative',
  MikroTik: 'mikrotik',
  'Active Directory': 'microsoft',
  'PCI tokenization': 'visa',
};

export function techIconSlug(label: string): string | undefined {
  if (TECH_SLUG_MAP[label]) return TECH_SLUG_MAP[label];
  const normalized = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '')
    .replace(/dotjs$/, 'dotjs');
  return normalized.length > 1 ? normalized : undefined;
}

export function techIconPath(label: string): string | undefined {
  if (SKILL_ICONS[label]) return skillImage(SKILL_ICONS[label]);
  const slug = techIconSlug(label);
  return slug ? skillImage(`${slug}.svg`) : undefined;
}
